#!/usr/bin/env node
// Renders infra/Caddyfile from headers.json + sites.json.
//
// The Caddyfile is generated rather than hand-written so the production headers
// cannot drift from the ones the Vite dev and preview servers send. Editing it
// by hand will be undone.
//
//   node infra/gen.mjs            write the Caddyfile
//   node infra/gen.mjs --check    exit 1 if the file on disk is out of date
//
// --check compares against the file's own contents rather than asking git,
// because a `git diff` gate silently passes when the Caddyfile is untracked.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const read = (name) => JSON.parse(readFileSync(join(here, name), 'utf8'))

const headers = read('headers.json')
const { domain, releaseRoot, sites } = read('sites.json')

const indent = (depth, line) => '\t'.repeat(depth) + line

const headerBlock = (entries, depth) =>
  Object.entries(entries).map(([name, value]) => indent(depth, `${name} "${value}"`))

const snippet = () => [
  '(ssheaders) {',
  indent(1, 'header {'),
  ...headerBlock(headers.document, 2),
  indent(2, '-Server'),
  indent(1, '}'),
  '',
  indent(1, `@immutable path ${headers.immutablePaths.join(' ')}`),
  ...Object.entries(headers.immutable).map(([name, value]) =>
    indent(1, `header @immutable ${name} "${value}"`),
  ),
  '',
  indent(1, `@revalidate path ${headers.revalidatePaths.join(' ')}`),
  ...Object.entries(headers.revalidate).map(([name, value]) =>
    indent(1, `header @revalidate ${name} "${value}"`),
  ),
  '}',
]

const siteBlock = ({ page, subdomain }) => [
  `${subdomain}.${domain} {`,
  indent(1, `root * ${releaseRoot}/${page}/current`),
  indent(1, 'import ssheaders'),
  indent(1, 'encode zstd gzip'),
  indent(1, 'file_server'),
  indent(1, 'try_files {path} /index.html'),
  '}',
]

const banner = [
  '# GENERATED by infra/gen.mjs from headers.json + sites.json — do not edit.',
  '# Regenerate with `npm run infra:gen`.',
  '#',
  `# Domain: ${domain}`,
  ...(domain.endsWith('.invalid')
    ? [
        '# This is a placeholder. `.invalid` is reserved by RFC 2606 so it can never',
        '# resolve, which keeps a half-configured Caddy from requesting a real',
        '# certificate. Set the real domain in sites.json before deploying.',
      ]
    : []),
  '',
]

const caddyfile = [...banner, ...snippet(), '', ...sites.flatMap(siteBlock)].join('\n') + '\n'

const out = join(here, 'Caddyfile')

if (process.argv.includes('--check')) {
  let current = null
  try {
    current = readFileSync(out, 'utf8')
  } catch {
    console.error(`infra/Caddyfile is missing. Run \`npm run infra:gen\`.`)
    process.exit(1)
  }

  if (current !== caddyfile) {
    console.error(
      'infra/Caddyfile is out of date with headers.json / sites.json.\n' +
        'Run `npm run infra:gen` and commit the result. Do not edit the Caddyfile by hand —\n' +
        'production headers have to come from the same source the dev server uses.',
    )
    process.exit(1)
  }

  console.log('infra/Caddyfile is up to date')
} else {
  writeFileSync(out, caddyfile)
  console.log(`wrote ${out} (${sites.length} site${sites.length === 1 ? '' : 's'})`)
}
