#!/usr/bin/env node
// Renders infra/Caddyfile from headers.json + sites.json.
//
// The Caddyfile is generated rather than hand-written so the production headers
// cannot drift from the ones the Vite dev server and tools/serve.mjs send.
// Editing it by hand will be undone.
//
//   node infra/gen.mjs            write the Caddyfile
//   node infra/gen.mjs --check    exit 1 if the file on disk is out of date
//
// --check compares against the file's own contents rather than asking git,
// because a `git diff` gate silently passes when the Caddyfile is untracked.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { allPages, cachePaths, readJson } from './cache-paths.mjs'

const here = dirname(fileURLToPath(import.meta.url))

const headers = readJson('headers.json')
const sites = readJson('sites.json')
const { domain, subdomain, releaseRoot } = sites

const host = `${subdomain}.${domain}`
const root = `${releaseRoot}/${subdomain}/current`
const { immutable, revalidate } = cachePaths(headers, sites)

const indent = (depth, line) => '\t'.repeat(depth) + line

const siteBlock = () => [
  `${host} {`,
  indent(1, `root * ${root}`),
  '',
  indent(1, 'header {'),
  ...Object.entries(headers.document).map(([name, value]) => indent(2, `${name} "${value}"`)),
  indent(2, '-Server'),
  indent(1, '}'),
  '',
  indent(1, `@immutable path ${immutable.join(' ')}`),
  ...Object.entries(headers.immutable).map(([name, value]) =>
    indent(1, `header @immutable ${name} "${value}"`),
  ),
  '',
  indent(1, `@revalidate path ${revalidate.join(' ')}`),
  ...Object.entries(headers.revalidate).map(([name, value]) =>
    indent(1, `header @revalidate ${name} "${value}"`),
  ),
  '',
  indent(1, 'encode zstd gzip'),
  // No try_files. None of these pages has a client-side router, so the only
  // thing a fallback would do is answer a missing .scsyndef or .wasm with
  // index.html and a 200 — a binary request served HTML, which surfaces as an
  // opaque parse failure instead of a 404. Every bug of that shape in this
  // project so far has presented as silence. file_server resolves /<page>/ to
  // that page's index.html through index_names, which is all that was wanted.
  indent(1, 'file_server'),
  '}',
]

const banner = [
  '# GENERATED by infra/gen.mjs from headers.json + sites.json — do not edit.',
  '# Regenerate with `npm run infra:gen`.',
  '#',
  `# ${host}`,
  ...allPages(sites).map(({ path, title }) => `#   ${path.padEnd(14)} ${title}`),
  ...(domain.endsWith('.invalid')
    ? [
        '#',
        '# This is a placeholder. `.invalid` is reserved by RFC 2606 so it can never',
        '# resolve, which keeps a half-configured Caddy from requesting a real',
        '# certificate. Set the real domain in sites.json before deploying.',
      ]
    : []),
  '',
]

const caddyfile = [...banner, ...siteBlock()].join('\n') + '\n'
const out = join(here, 'Caddyfile')

if (process.argv.includes('--check')) {
  let current = null
  try {
    current = readFileSync(out, 'utf8')
  } catch {
    console.error(`infra/Caddyfile is missing. Run \`npm run infra:gen\`.`)
    process.exit(1)
  }

  if (current !== caddyfile) {
    console.error(
      'infra/Caddyfile is out of date with headers.json / sites.json.\n' +
        'Run `npm run infra:gen` and commit the result. Do not edit the Caddyfile by hand —\n' +
        'production headers have to come from the same source the dev server uses.',
    )
    process.exit(1)
  }

  console.log('infra/Caddyfile is up to date')
} else {
  writeFileSync(out, caddyfile)
  console.log(`wrote ${out} (${allPages(sites).length} pages on ${host})`)
}
