import { describe, expect, it } from 'vitest'
import { showerFrom, SILENCE_BELOW } from '../src/mapping.ts'
import { fold, lincurve, linexp, RESTING, type Motion } from '@ss/motion'

// Every expectation below is sclang's own output, generated by running the
// mappings from droplet.sc's `~next` with their real arguments. Nothing here is
// derived from the TypeScript — that would only prove it agrees with itself.
//
// These curves are the instrument. A lincurve reimplemented as a lerp compiles,
// runs, and sounds subtly wrong in a way no other test would notice.

/** `gyroYFiltered.lincurve(-1, 1, 0.5, 0.075)` — default curve, -4. */
const SC_DUR: [number, number][] = [
  [-1, 0.5],
  [-0.6, 0.26159833086752],
  [-0.21, 0.15624329302657],
  [0, 0.1256612418594],
  [0.21, 0.10556740239659],
  [0.6, 0.084717777465961],
  [1, 0.075],
]

/** `gyroYFiltered.lincurve(-1, 1, 0, 1, -2)`. */
const SC_AMP: [number, number][] = [
  [-1, 0],
  [-0.6, 0.38128068322068],
  [-0.21, 0.63163812993551],
  [0, 0.73105857863],
  [0.21, 0.81164722806905],
  [0.6, 0.92302075767912],
  [1, 1],
]

/** `roll.lincurve(-1, 1, 0.01, 14000, -2)` — the wobble ceiling. */
const SC_WOBBLE_CEILING: [number, number][] = [
  [-1, 0.01],
  [-0.6, 5337.9357522827],
  [-0.21, 8842.9375027159],
  [0, 10234.822790234],
  [0.6, 12922.2913773],
  [1, 14000],
]

/** `side.lincurve(0, 1, 0.05, 3, -1)`. */
const SC_DECAY: [number, number][] = [
  [0, 0.05],
  [0.25, 1.0822994258384],
  [0.5, 1.8862550270455],
  [0.75, 2.5123762788202],
  [1, 3],
  [1.6, 3],
]

/** `mass.lincurve(0, 2.5, 0.53, 0.95, 2)` — a positive curve, for contrast. */
const SC_ROOM: [number, number][] = [
  [0, 0.53],
  [0.5, 0.56233128177477],
  [1.25, 0.6429553969754],
  [2, 0.78986211304731],
  [2.5, 0.95],
]

describe('lincurve matches SuperCollider', () => {
  it.each(SC_DUR)('dur at %s', (input, expected) => {
    expect(lincurve(input, -1, 1, 0.5, 0.075)).toBeCloseTo(expected, 10)
  })

  it.each(SC_AMP)('amp at %s', (input, expected) => {
    expect(lincurve(input, -1, 1, 0, 1, -2)).toBeCloseTo(expected, 10)
  })

  it.each(SC_WOBBLE_CEILING)('wobble ceiling at %s', (input, expected) => {
    expect(lincurve(input, -1, 1, 0.01, 14000, -2)).toBeCloseTo(expected, 6)
  })

  it.each(SC_DECAY)('decay at %s', (input, expected) => {
    expect(lincurve(input, 0, 1, 0.05, 3, -1)).toBeCloseTo(expected, 10)
  })

  it.each(SC_ROOM)('room at %s', (input, expected) => {
    expect(lincurve(input, 0, 2.5, 0.53, 0.95, 2)).toBeCloseTo(expected, 10)
  })

  it('bends toward outMax on a negative curve, not outMin', () => {
    // The thing I had backwards. At the input midpoint a curve of -4 is 88% of
    // the way to outMax, which is why droplet plays across most of its
    // tilt and only stops at the very bottom.
    expect(lincurve(0, -1, 1, 0, 1, -4)).toBeCloseTo(0.8807970779778824, 10)
    // A positive curve does the opposite.
    expect(lincurve(0, -1, 1, 0, 1, 4)).toBeLessThan(0.2)
  })

  it('falls back to linear where SuperCollider does', () => {
    expect(lincurve(0, -1, 1, 0, 10, 0)).toBeCloseTo(5, 10)
    expect(lincurve(0, -1, 1, 0, 10, 0.0000001)).toBeCloseTo(5, 6)
  })

  it('clips rather than extrapolating past the input range', () => {
    expect(lincurve(-50, -1, 1, 0.5, 0.075, -4)).toBeCloseTo(0.5, 10)
    expect(lincurve(50, -1, 1, 0.5, 0.075, -4)).toBeCloseTo(0.075, 10)
  })
})

describe('linexp matches SuperCollider', () => {
  it('reproduces the value sclang gives', () => {
    expect(linexp(0.4, 0, 1.8, 2, 0.12)).toBeCloseTo(1.0703062249359, 10)
  })

  it('hits both ends exactly', () => {
    expect(linexp(0, 0, 1.8, 2, 0.12)).toBeCloseTo(2, 10)
    expect(linexp(1.8, 0, 1.8, 2, 0.12)).toBeCloseTo(0.12, 10)
  })
})

describe('fold matches SuperCollider', () => {
  it.each([
    [-0.9, -0.1],
    [-0.5, -0.5],
    [-0.2, -0.2],
    [0.2, 0.2],
    [0.5, 0.5],
    [0.9, 0.1],
  ])('fold(%s, -0.5, 0.5)', (input, expected) => {
    expect(fold(input, -0.5, 0.5)).toBeCloseTo(expected, 10)
  })
})

const motion = (over: Partial<Motion> = {}): Motion => ({ ...RESTING, live: true, ...over })

describe('the shower a pose asks for', () => {
  it('plays hard when the phone is held level', () => {
    // Not what the sign of the curve suggests, and worth pinning: amp at a
    // level phone is 0.73, well above the threshold. Silence lives at the
    // upright end, not at rest.
    const level = showerFrom(motion({ pitch: 0 }))
    expect(level.amp).toBeCloseTo(0.73105857863, 10)
    expect(level.level).toBeGreaterThan(SILENCE_BELOW)
  })

  it('stops when the phone is stood upright', () => {
    // The flip. pitch is +1 standing up, which the mapping negates, so that is
    // the silent end — hold it flat like a bowl and it plays, stand it up and
    // it stops.
    expect(showerFrom(motion({ pitch: 1 })).level).toBeLessThan(SILENCE_BELOW)
    // The crossing is at a gyroY of about -0.78, so a phone most of the way up.
    expect(showerFrom(motion({ pitch: 0.85 })).level).toBeLessThan(SILENCE_BELOW)
    expect(showerFrom(motion({ pitch: 0.7 })).level).toBeGreaterThan(SILENCE_BELOW)
  })

  it('plays faster as the phone is laid flat', () => {
    // dur is the gap between drops, so faster is smaller.
    expect(showerFrom(motion({ pitch: -1 })).dur).toBeLessThan(
      showerFrom(motion({ pitch: 1 })).dur,
    )
  })

  it('never asks for a dur outside the SynthDef spec', () => {
    // ssp_drop_clock declares dur as 0.075..0.5. A mapping that reached past
    // its spec would be clamped by mapSpec and the gesture would go dead at
    // one end with nothing to show why.
    for (let pitch = -1; pitch <= 1; pitch += 0.05) {
      const shower = showerFrom(motion({ pitch }))
      expect(shower.dur).toBeGreaterThanOrEqual(0.075)
      expect(shower.dur).toBeLessThanOrEqual(0.5)
    }
  })

  it('keeps the reverb below the clip in the graph', () => {
    // FreeVerb2 above 0.95 does not decay, it grows. The SynthDef clips, and
    // the mapping should never be asking for it in the first place.
    for (let shake = 0; shake <= 1; shake += 0.02) {
      expect(showerFrom(motion({ shake })).room).toBeLessThanOrEqual(0.95)
    }
  })

  it('lengthens the tail and opens the room as the phone is moved', () => {
    const calm = showerFrom(motion({ accelY: 0, accelZ: 0, shake: 0 }))
    const shaken = showerFrom(motion({ accelY: 0.7, accelZ: 0.6, shake: 0.9 }))

    expect(shaken.decay).toBeGreaterThan(calm.decay)
    expect(shaken.room).toBeGreaterThan(calm.room)
  })

  it('needs both roll and a flick to reach the top of the wobble', () => {
    // Roll sets the ceiling, the flick travels toward it. Rolled but still is
    // nearly as quiet as unrolled, which is the two-gesture shape the original
    // has and the reason this voice is never static.
    const still = showerFrom(motion({ roll: 1, accelY: 0, accelZ: 0 }))
    const flicked = showerFrom(motion({ roll: 1, accelY: 0.6, accelZ: 0.5 }))
    const flat = showerFrom(motion({ roll: -1, accelY: 0.6, accelZ: 0.5 }))

    expect(still.wobble).toBeLessThan(2)
    expect(flicked.wobble).toBeGreaterThan(10_000)
    expect(flat.wobble).toBeLessThan(2)
  })

  it('stays inside the values the voice was built for', () => {
    for (let n = 0; n < 500; n++) {
      const shower = showerFrom(
        motion({
          pitch: Math.sin(n) ,
          roll: Math.cos(n * 1.7),
          accelY: Math.sin(n * 0.3),
          accelZ: Math.cos(n * 0.9),
          shake: Math.abs(Math.sin(n * 0.11)),
        }),
      )
      for (const [name, value] of Object.entries(shower)) {
        expect(Number.isFinite(value), `${name} was ${value}`).toBe(true)
      }
      expect(shower.decay).toBeLessThanOrEqual(3)
      expect(shower.wobble).toBeLessThanOrEqual(14_000)
      expect(shower.amp).toBeLessThanOrEqual(1)
      expect(shower.amp).toBeGreaterThanOrEqual(0)
    }
  })
})
