import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  initialValues,
  isDiscrete,
  mapSpec,
  unmapSpec,
  type ControlSpec,
  type SynthDefContract,
} from '../src/contract.ts'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')

// Ground truth generated by SuperCollider itself, via sidecar/tests/fixtures.
// The point of this file is that a page's sliders and the sclang rig's sliders
// move a control identically — if the two mappings drift, the sound you tuned
// by ear is not the sound the page makes.
interface WarpTruth {
  units: number[]
  cases: { label: string; spec: ControlSpec; mapped: number[]; roundTrip: number[] }[]
}

const truth = JSON.parse(
  readFileSync(join(repoRoot, 'sidecar/tests/fixtures/warp-truth.json'), 'utf8'),
) as WarpTruth

describe('the truth table', () => {
  it('covers every warp the specs use', () => {
    const warps = new Set(truth.cases.map((c) => String(c.spec.warp)))
    expect(warps).toContain('linear')
    expect(warps).toContain('exp')
    expect(warps).toContain('amp')
    expect([...warps].some((w) => Number.isFinite(Number(w)))).toBe(true)
  })
})

describe.each(truth.cases.map((c) => [c.label, c] as const))('%s', (_label, testCase) => {
  it('maps exactly as SuperCollider does', () => {
    for (const [index, unit] of truth.units.entries()) {
      const expected = testCase.mapped[index] as number
      expect(mapSpec(testCase.spec, unit), `unit ${unit}`).toBeCloseTo(expected, 6)
    }
  })

  it('round-trips through unmap', () => {
    for (const [index, unit] of truth.units.entries()) {
      const expected = testCase.roundTrip[index] as number
      const actual = unmapSpec(testCase.spec, mapSpec(testCase.spec, unit))
      expect(actual, `unit ${unit}`).toBeCloseTo(expected, 6)
    }
  })

  it('stays inside its own range', () => {
    const lo = Math.min(testCase.spec.min, testCase.spec.max)
    const hi = Math.max(testCase.spec.min, testCase.spec.max)
    for (const unit of [0, 0.3, 0.5, 0.9, 1]) {
      const value = mapSpec(testCase.spec, unit)
      expect(value).toBeGreaterThanOrEqual(lo)
      expect(value).toBeLessThanOrEqual(hi)
    }
  })
})

describe('clamping', () => {
  const spec = truth.cases[0]?.spec as ControlSpec

  it('clips a unit value outside 0..1, as ControlSpec.map does', () => {
    expect(mapSpec(spec, -5)).toBe(mapSpec(spec, 0))
    expect(mapSpec(spec, 5)).toBe(mapSpec(spec, 1))
  })
})

describe('discrete controls', () => {
  it('recognises a stepped spec', () => {
    const stepped = truth.cases.find((c) => c.label === 'stepped')?.spec as ControlSpec
    expect(isDiscrete(stepped)).toBe(true)
  })

  it('treats a continuous spec as continuous', () => {
    const linear = truth.cases.find((c) => c.label === 'linear')?.spec as ControlSpec
    expect(isDiscrete(linear)).toBe(false)
  })

  it('quantises to whole steps, so a selector never lands between values', () => {
    // SuperCollider's Select.ar truncates toward zero, so a fractional value
    // silently picks the wrong branch rather than erroring.
    const stepped = truth.cases.find((c) => c.label === 'stepped')?.spec as ControlSpec
    for (const unit of [0, 0.2, 0.4, 0.6, 0.8, 1]) {
      expect(Number.isInteger(mapSpec(stepped, unit)), `unit ${unit}`).toBe(true)
    }
  })
})

describe('an exponential spec that includes zero', () => {
  it('refuses rather than returning NaN', () => {
    // log(0) is -Infinity, so the ratio is undefined. Reporting it beats
    // producing a slider whose every position reads NaN.
    const broken: ControlSpec = {
      name: 'broken',
      min: 0,
      max: 100,
      warp: 'exp',
      step: 0,
      default: 0,
      units: '',
    }
    expect(() => mapSpec(broken, 0.5)).toThrow(/cannot include or cross zero/)
  })
})

describe('the shipped contracts', () => {
  const manifest = JSON.parse(
    readFileSync(join(repoRoot, 'sidecar/dist/manifest.json'), 'utf8'),
  ) as { defs: { name: string; contract: SynthDefContract }[] }

  it.each(manifest.defs.map((d) => [d.name, d.contract] as const))(
    '%s maps every spec without throwing',
    (_name, contract) => {
      for (const spec of contract.specs) {
        for (const unit of [0, 0.25, 0.5, 0.75, 1]) {
          const value = mapSpec(spec, unit)
          expect(Number.isFinite(value), `${spec.name} at ${unit}`).toBe(true)
        }
      }
    },
  )

  it.each(manifest.defs.map((d) => [d.name, d.contract] as const))(
    '%s declares a default inside its own range',
    (_name, contract) => {
      for (const spec of contract.specs) {
        const lo = Math.min(spec.min, spec.max)
        const hi = Math.max(spec.min, spec.max)
        expect(spec.default, spec.name).toBeGreaterThanOrEqual(lo)
        expect(spec.default, spec.name).toBeLessThanOrEqual(hi)
      }
    },
  )

  it.each(manifest.defs.map((d) => [d.name, d.contract] as const))(
    '%s gives initialValues a number for every spec and frozen control',
    (_name, contract) => {
      const values = initialValues(contract)
      for (const spec of contract.specs) expect(values).toHaveProperty(spec.name)
      for (const frozen of contract.frozen) expect(values[frozen.name]).toBe(frozen.value)
      // Supplied controls are deliberately absent: the pattern provides them.
      for (const supplied of contract.supplied) expect(values).not.toHaveProperty(supplied.name)
    },
  )
})
