#!/usr/bin/env node
// Regenerate docs/UNKNOWN-PARAMS.md from the staged contracts.
//
//   npm run build && npm run unknown-params
//
// Reads what the inference actually produced rather than re-deriving it, so the
// report cannot drift from the contracts the page is using.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const synthdefs = join(repoRoot, 'apps/playground/public/vendor/supersonic/synthdefs')

const byName = new Map()
let withRange = 0
let withoutRange = 0

for (const file of readdirSync(synthdefs).filter((name) => name.endsWith('.contract.json'))) {
  const contract = JSON.parse(readFileSync(join(synthdefs, file), 'utf8'))
  if (contract.source !== 'inferred') continue

  const def = file.replace('.contract.json', '').replace('sonic-pi-', '')
  withRange += contract.specs.length

  for (const unknown of contract.unknown) {
    withoutRange++
    if (!byName.has(unknown.name)) byName.set(unknown.name, { defaults: new Set(), defs: [] })
    const entry = byName.get(unknown.name)
    entry.defaults.add(Number(unknown.default.toFixed(4)))
    entry.defs.push(def)
  }
}

const rows = [...byName].sort(
  (a, b) => b[1].defs.length - a[1].defs.length || a[0].localeCompare(b[0]),
)
const coverage = ((withRange / (withRange + withoutRange)) * 100).toFixed(1)

const header = `# Parameters still without a range

The vendored Sonic Pi defs carry no metadata, so their control ranges are inferred from naming
conventions — see [SYNTHDEFS.md](SYNTHDEFS.md#inferred-contracts). **${coverage}% of parameters are
covered.** These ${rows.length} names are not, so they appear in the UI as a value with no control.

That is deliberate. A parameter with an invented range is worse than one with none, because the
slider looks authoritative and is not.

> Generated by \`npm run unknown-params\` from the staged contracts. Do not edit by hand.

## How to supply one

Add it to [\`param-ranges.json\`](../param-ranges.json) at the repo root — data, not code:

\`\`\`json
"depth": [0, 1, "linear", 0]
\`\`\`

\`[min, max, warp, step, units?]\`. Warp is \`"linear"\`, \`"exponential"\`, \`"amp"\`, or a number for a
curve. Step is \`0\` for continuous, \`1\` for a stepper or a switch. An exponential range cannot
include or cross zero.

Then \`npm run build\`, and every def using that name picks it up.

### When a name means more than one thing

Some do. \`depth\` is milliseconds in \`fx_flanger\`, a modulation index in \`fm\`, and a 0–1 amount in
\`fx_tremolo\` — one global range would be wrong everywhere except by accident. Scope those to a def:

\`\`\`json
"fx_flanger.depth": [0, 20, "linear", 0, "ms"],
"fx_tremolo.depth": [0, 1, "linear", 0]
\`\`\`

A scoped key wins over a bare name, which wins over the pattern rules. Drop the \`sonic-pi-\` prefix.

### Reading the defaults

The defaults column is the best available clue, and sometimes decisive. Two worked examples:

- **\`cutoff\`** defaults to 83, 100, 102, 110 across the defs that have it. Absurd as filter
  frequencies in Hz, ordinary as MIDI notes — so the inferred range is \`0–130\`, not a frequency.
- **\`centre\`** defaults to 100 in all four bandpass filters, which is the same convention. A
  −1…1 range would put every one of them at effectively 0 Hz, passing nothing.

If a default sits outside the range you supply it is clamped, and the original is kept on the spec
as \`declaredDefault\` rather than being lost.

## The list

Defaults are every distinct value seen across the defs that declare the parameter.

| parameter | defs | defaults seen | used by |
|---|---|---|---|
`

const table = rows
  .map(([name, entry]) => {
    const defaults = [...entry.defaults].sort((a, b) => a - b)
    const shown = defaults.length > 6 ? `${defaults.slice(0, 6).join(', ')}, …` : defaults.join(', ')
    const defs =
      entry.defs.length > 4 ? `${entry.defs.slice(0, 4).join(', ')}, …` : entry.defs.join(', ')
    return `| \`${name}\` | ${entry.defs.length} | ${shown} | ${defs} |`
  })
  .join('\n')

writeFileSync(join(repoRoot, 'docs/UNKNOWN-PARAMS.md'), `${header}${table}\n`)

console.log(`${coverage}% covered — ${rows.length} names still without a range`)
